# +--------------------------------------------------------------------+ #
# <               RedProtect World configuration File                  > #
# <--------------------------------------------------------------------> #
# <       This is the configuration file, feel free to edit it.        > #
# +--------------------------------------------------------------------+ #
# <        You can see the complete commented version of this          > #
# <       configuration file in this link: http://goo.gl/EAepC7        > #
# +--------------------------------------------------------------------+ #

file-type: yml
auto-save-interval-seconds: 1200
mysql:
  db-name: redprotect
  user-name: root
  user-pass: redprotect
  host: localhost
  max-connections-limit: 1000
allowed-claim-worlds:
- example_world
drop-type: keep
debug-messages: false
preferred-permissions: Detect
limit-amount: 8000
height-start: 0
block-id: FENCE
max-scan: 600
backup: true
adminWandID: 374
infoWandID: 339
use-private: true
allowed-private-blocks:
- DISPENSER
- NOTE_BLOCK
- BED_BLOCK
- CHEST
- WORKBENCH
- FURNACE
- JUKEBOX
- ENCHANTMENT_TABLE
- BREWING_STAND
- CAULDRON
- ENDER_CHEST
- BEACON
- TRAPPED_CHEST
- HOPPER
- DROPPER
allow-private-outside: false
anti-hopper: true
notify-region-enter: true
notify-region-enter-mode: BOSSBAR
welcome-notify-mode: BOSSBAR
date-format: dd/MM/yyyy
record-player-visit-method: ON-LOGIN
netherProtection:
  maxYsize: 128
  execute-cmd: spawn {player}
flags:
  pvp: false
  chest: false
  lever: false
  button: false
  door: false
  spawn-monsters: true
  spawn-animals: true
  passives: false
  flow: true
  fire: false
  minecart: false
  allow-home: false
purge:
  enabled: false
  remove-oldest: 90
  ignore-regions-from-players:
update-check:
  enable: true
  auto-update: false