# +--------------------------------------------------------------------+ #
# <               RedProtect World configuration File                  > #
# <--------------------------------------------------------------------> #
# <       This is the configuration file, feel free to edit it.        > #
# +--------------------------------------------------------------------+ #
# <        You can see the complete commented version of this          > #
# <       configuration file in this link: https://goo.gl/SEbYBZ       > #
# +--------------------------------------------------------------------+ #

config-version: 6.4
debug-messages: false
log-actions: true
language: EN-US
file-type: yml
flat-file:
  auto-save-interval-seconds: 3600
  backup: true
  max-backups: 10
mysql:
  db-name: redprotect
  user-name: root
  user-pass: redprotect
  host: localhost
  region-cache-minutes: 2
region-settings:
  default-owner: '#server#'
  world-colors:
  border:
    material: GLOWSTONE
    time-showing: 5
  region-list:
    simple-listing: true
    hover-and-click-teleport: true
  autoexpandvert-ondefine: true
  anti-hopper: true
  drop-type: keep
  limit-amount: 8000
  claim-amount: 20
  block-id: FENCE
  max-scan: 600
  date-format: dd/MM/yyyy
  record-player-visit-method: ON-LOGIN
  allow-sign-interact-tags:
  - Admin Shop
  - '{membername}'
allowed-claim-worlds:
- example_world
wands:
  adminWandID: 374
  infoWandID: 339
private:
  use: true
  allow-outside: false
  allowed-blocks-use-ids: false
  allowed-blocks:
  - DISPENSER
  - NOTE_BLOCK
  - BED_BLOCK
  - CHEST
  - WORKBENCH
  - FURNACE
  - JUKEBOX
  - ENCHANTMENT_TABLE
  - BREWING_STAND
  - CAULDRON
  - ENDER_CHEST
  - BEACON
  - TRAPPED_CHEST
  - HOPPER
  - DROPPER
notify:
  region-enter: true
  region-exit: true
  region-enter-mode: BOSSBAR
  welcome-mode: BOSSBAR
netherProtection:
  maxYsize: 128
  execute-cmd: 
  - spawn {player}
server-protection:
  deny-potions:
  - INVISIBILITY
  deny-playerdeath-by:
  - SUFFOCATION
  deny-commands-on-worlds:
    world:
    - command
  nickname-cap-filter:
    enabled: false
  sign-spy:
    enabled: false
    only-console: true
flags:
  pvp: false
  chest: false
  lever: false
  button: false
  door: false
  allow-potions: true
  smart-door: true
  spawn-monsters: true
  spawn-animals: true
  passives: false
  flow: true
  fire: false
  minecart: false
  allow-home: false
  allow-magiccarpet: true
  mob-loot: false
  flow-damage: false
flags-configuration:
  effects-duration: 5
  enabled-flags:
  - pvp
  - chest
  - lever
  - button
  - door
  - smart-door
  - spawn-monsters
  - spawn-animals
  - passives
  - flow
  - fire
  - minecart
  - allow-potions
  - allow-home
  - allow-magiccarpet
  - mob-loot
  - flow-damage
  pvparena-nopvp-kick-cmd: spawn {player}
  change-flag-delay:
    enable: true
    seconds: 10
    flags:
    - pvp
purge:
  enabled: false
  remove-oldest: 90
  ignore-regions-from-players:
sell:
  enabled: false
  sell-oldest: 60
  ignore-regions-from-players:
update-check:
  enable: true
  auto-update: false
performance:
  disable-onPlayerMoveEvent-handler: false
  disable-PistonEvent-handler: false
hooks:
  essentials:
    import-lastvisits: false
  furniturelib:
    purge:
       ignore-regions-from-players:
       