# +--------------------------------------------------------------------+ #
# <               RedProtect World configuration File                  > #
# <--------------------------------------------------------------------> #
# <       This is the configuration file, feel free to edit it.        > #
# +--------------------------------------------------------------------+ #
# <        You can see the complete commented version of this          > #
# <       configuration file in this link: https://goo.gl/SEbYBZ       > #
# +--------------------------------------------------------------------+ #

config-version: 7.4
# Enable debug messages
debug-messages: false

# Log all commands used by players
log-actions: true

# Available: en-EN, pt-BR, zh-CN, de-DE
language: en-EN

# Available: yml and mysql
file-type: yml

# If file-type: yml, configuration:
flat-file:
  # Want to save the regions in your ow files? This can improve performance because theres a new system where the autosave will save only modified regions and not all on auto-save.
  region-per-file: false
  auto-save-interval-seconds: 3600
  backup: true
  max-backups: 10

# If file-type: mysql, configuration:
mysql:
  db-name: redprotect
  table-prefix: rp_
  user-name: root
  user-pass: redprotect
  host: localhost
  # Regions stay loaded on memory for:
  region-cache-minutes: 2

region-settings:
  # Claim mode allowed for normal players (without permission 'redprotect.admin.claim'). Options: BLOCK, WAND or BOTH.
  # -> If BLOCK, the players needs to surround your house with the block type in configuration, and place a sign under this fence with [rp] on first line.
  # -> If WAND, the players will need a wand (default glass_bottle), click on two point of your region, and then use /rp claim [name of region] to claim te region.
  # -> If BOTH, will allow both claim type protections.
  # Dont need the claim and create perms anymore.
  claim-type:
  # The name of leader for regions created with /rp define or regions without leaders. 
  default-leader: '#server#'
  # Colors of world to show on /rp info and /rp list.
  world-colors:
  # Border block type when use /rp border.
  border:
    material: GLOWSTONE
    time-showing: 10
  region-list:
    # Show simple list with only name of region or all region info.
    simple-listing: true
    # If running server 1.8+ enable hover and teleport click on simple list.
    hover-and-click-teleport: true
    # Show region areas on list?
    show-area: true
  # Automatically set max y to 256 and min y to 0 (sky to bedrock).
  autoexpandvert-ondefine: true
  # Deny break/place blocks under chests.
  anti-hopper: true
  # Modes of protection regions
  claim-modes:
    # Default modes for claim regions. Modes available: keep, drop, remove or give. 
    # keep: Nothing happens
    # drop: Will drop all protection blocks
    # remove: Will remove all protection blocks
    # give: Give back the protection blocks to player, and drop(on player location) if players's inventory is full
    mode: keep
    # Allow players to decide what mode to use? If true, the player need to set the line 4 of the sign with [keep], [drop], [remove], [give] or a translation you is using on 'lang.ini'.
    allow-player-decide: false
    # If 'allow-player-decide' is true, player need to have the permission 'redprotect.use-claim-modes' to use modes on signs.
    use-perm: false
  # Limit of blocks/region until the player have other blocks permission.
  limit-amount: 8000
  # Limit of claims a player can have until have other permission fro claims.
  claim-amount: 20
  # Block used to protect regions.
  block-id: FENCE
  # Ammount of blocks to scan on place sign to claim a region. Consider this the max area.
  max-scan: 600
  # Time format to use with data and time infos.
  date-format: dd/MM/yyyy
  # Register player visits on... Available: ON-LOGIN, ON-REGION-ENTER.
  record-player-visit-method: ON-LOGIN
  # Allow players without permissions to interact with signs starting with this tags.
  allow-sign-interact-tags:
  - Admin Shop
  - '{membername}'
  # Time in seconds to wait player accept leadership request
  leadership-request-time: 20
  # Enable flag signs
  enable-flag-sign: true
  # Deny players to build near other regions. Distance in blocks. 0 to disable and > 0 to enable distance.
  deny-build-near: 0

  rent:
    # Set the default rent level of players renting region. Options: member, admin, leader.
    default-level: admin
    # Allow who pay for rent to add more players in rent regions?
    add-player: false
    # The amount of days or mounts the command to renew will be added. The sintax is: <number>:<type>. The types are: DAY or MONTH.
    command-renew-adds: 1:MONTH
    # Renew in anytime or only on renew date?
    renew-anytime: false

  # First home settings
  first-home:
    # Player can remove the protectio of first home after this amount of claims. Use -1 to do not allow to delete.
    can-delete-after-claims: 10  

# World that player can claim regions.
allowed-claim-worlds:
- example_world

# Worlds where players can't build without claim.
needed-claim-to-build:
  worlds:
  - example_world
  # Allow only protection blocks id.
  allow-only-protections-blocks: true
 
wands:
  # Item used to define and redefine regions.
  adminWandID: 374
  # Item used to check regions.
  infoWandID: 339

private:
  # Enable private signs?
  use: true
  # Allow private signs outside regions
  allow-outside: false
  # Use number IDs instead item names?
  allowed-blocks-use-ids: false
  # Block allowed to lock with private signs.
  allowed-blocks:
  - DISPENSER
  - NOTE_BLOCK
  - BED_BLOCK
  - CHEST
  - WORKBENCH
  - FURNACE
  - JUKEBOX
  - ENCHANTMENT_TABLE
  - BREWING_STAND
  - CAULDRON
  - ENDER_CHEST
  - BEACON
  - TRAPPED_CHEST
  - HOPPER
  - DROPPER

notify:
  # Show region info when enter a region.
  region-enter: true
  # Show region info(or wilderness message) when exit a region.
  region-exit: true
  # How to show the messages? Available: BOSSBAR, CHAT. If plugin BoobarApi not installed, will show on chat.
  region-enter-mode: BOSSBAR
  # Where to show the welcome message (/rp wel <message>)? Available: BOSSBAR, CHAT.
  welcome-mode: BOSSBAR

netherProtection:
  # Max size of your world nether.
  maxYsize: 128
  # Execute this if player go up to maxYsize of nether.
  execute-cmd: 
  - spawn {player}

server-protection:
  # List of potions the player cant use on server. Here the PotioTypes: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionType.html
  deny-potions:
  - INVISIBILITY
  # List of causes the player cant die/take damage for. here the list of DamageCauses: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
  deny-playerdeath-by:
  - SUFFOCATION
  # Deny certain commands on specific worlds.
  deny-commands-on-worlds:
    world:
    - command
  # Deny players with same nick but cap diferences to join on server (most used on offline severs).
  nickname-cap-filter:
    enabled: false
  # Show all lines of a sign when player place signs in any world.
  sign-spy:
    enabled: false
    # Show only on console or in-game too?
    only-console: true
  teleport-player:
    # Teleport player on join the server.
    on-join:
       enable: false
       # The player need to be in this world to be teleported? Use 'none' for all worlds.
       need-world-to-teleport: none
       # The location, using as world, x, y, z.
       location: world, 0, 90, 0
    # Teleport player on logout the server.
    on-leave:    
       enable: false
       need-world-to-teleport: none
       location: world, 0, 90, 0
  # Deny structures like trees to bypass region borders?
  deny-structure-bypass-regions: true
  
  # Enable kill aura or freekill checker?
  check-killaura-freekill:
    enable: false
    # This will count every block the player wall without fail to aim on player
    check-rate: 30
    # What multiples of check-rate is considered kh or fk?
    rate-multiples: 5
    # Time to reset checks between attacker hits.
    time-between-trys: 3
    # Debug everu try? Used to see the try count on every block the player walk. Will be sequential if the player is using kill aura and will go to more than 60, 80 more than 100 if is free kill.
    debug-trys: false
    
  # Test hack client (beta)
  check-player-client: true

# Default values for new regions.
flags:
  pvp: false
  chest: false
  lever: false
  button: false
  door: false
  allow-potions: true
  smart-door: true
  spawn-monsters: true
  spawn-animals: true
  passives: false
  flow: true
  fire: false
  minecart: false
  allow-home: false
  allow-magiccarpet: true
  mob-loot: false
  flow-damage: false
  iceform-player: true
  iceform-world: true
  allow-fly: false
  teleport: false
  clan: ''
  ender-chest: true

flags-configuration:
  # Duration for timed flags like potions effects, jump, etc.
  effects-duration: 5
  # Flags enabled to players use with commands and flag Gui.
  enabled-flags:
  - pvp
  - chest
  - lever
  - button
  - door
  - smart-door
  - spawn-monsters
  - spawn-animals
  - passives
  - flow
  - fire
  - minecart
  - allow-potions
  - allow-home
  - allow-magiccarpet
  - mob-loot
  - flow-damage
  - iceform-player
  - iceform-world
  - allow-fly
  - teleport
  - clan
  - ender-chest
  
  # Command to use if players with pvp off enter in a region with 'pvparena' enabled.
  pvparena-nopvp-kick-cmd: spawn {player}
  # Delay the player can change a flag after last change.
  change-flag-delay:
    enable: true
    seconds: 10
    # List of flags the player will need to wait to change.
    flags:
    - pvp

# Remove regions after x time the player dont came online.
purge:
  enabled: false
  remove-oldest: 90
  # Hook with WorldEdit, will regen only the region areas to bedrock to sky. Theres no undo for this action!
  regen:
    enable: false
    # Max area size to automatic regen the region.
    max-area-regen: 500
    # Show regen logs if using AsyncWorldEdit.
    awe-logs: true
  ignore-regions-from-players:
  
# Put regions to sell after x time the player dont came online.
sell:
  enabled: false
  sell-oldest: 60
  ignore-regions-from-players:
  
# Check for updates?
update-check:
  enable: true
  auto-update: false

performance:
  # Disable player move event to improve performance? Note: Disabling this will make some flags do not work, like deny enter, execute commands and effects.
  disable-onPlayerMoveEvent-handler: false
  piston:
    # Disable piston track? Disabling this will allow players to get blocks from protected regions to unprotected using pistons.
    disable-PistonEvent-handler: false
    use-piston-restricter: false
    # Fire the piston extract/retract every x ticks. Server default is 1 tick/event. Value in ticks.
    restrict-piston-event: 10

# This is the schematics configs for RedProtect.
schematics:
  # Schematic file name to use with /rp start.
  first-house-file: 'house1.schematic'

hooks:
  essentials:
    # Import last visits from Essentials to RedProtect Regions.
    import-lastvisits: false
  dynmap:
    # Enable hook to show all regions on dynmap plugin?
    enable: true
    # Hide the Redprotect tab group by default?
    hide-by-default: true
    # Group to show on hide/show tab map.
    marks-groupname: RedProtect
    # If you use another region mark plugin.
    layer-priority: 10
    # Show names under regions.
    show-label: true
    # Show icons under regions.
    show-icon: true
    # Icon name to show under regions. All icons are available here: http://i.imgur.com/f61GPoE.png
    marker-icon: shield
    # Show leaders and admin?
    show-leaders-admins: true
    # Cuboid region config.
    cuboid-region:
       enabled: true
       if-disable-set-center: 60
    min-zoom: 0
  magiccarpet:
    # Fix pistons allow get mc blocks.
    fix-piston-getblocks: true
  armor-stands:
    spawn-arms: true
  mcmmo:
    # Fix players leveling with creeper explosions on flag fire disabled.
    fix-acrobatics-fireoff-leveling: true
    # Fix the ability berserk making players and mobs invisible around who activated the ability.
    fix-berserk-invisibility: true
  worldedit:
    # Use WorldEdit to paste newbie home-schematics (/rp start)? *RedProtect already can paste schematics without WorldEdit, but dont support NBT tags like chest contents and sign messages.
    use-for-schematics: true    
  asyncworldedit:
    # Use AsyncWorldEdit for regen regions? (need WorldEdit).
    use-for-regen: false
  factions:
    # Allow players claim Factions chunks under Redprotect regions?
    claim-over-rps: false    