# +--------------------------------------------------------------------+ #
# <               RedProtect World configuration File                  > #
# <--------------------------------------------------------------------> #
# <       This is the configuration file, feel free to edit it.        > #
# +--------------------------------------------------------------------+ #
# <        You can see the complete commented version of this          > #
# <       configuration file in this link: http://goo.gl/EAepC7        > #
# +--------------------------------------------------------------------+ #

config-version: 5.0
debug-messages: false
file-type: yml
flat-file:
  auto-save-interval-seconds: 1200
  backup: true
mysql:
  db-name: redprotect
  user-name: root
  user-pass: redprotect
  host: localhost
  region-cache-minutes: 2
region-settings:
  anti-hopper: true
  drop-type: keep
  limit-amount: 8000
  height-start: 0
  block-id: FENCE
  max-scan: 600
  date-format: dd/MM/yyyy
  record-player-visit-method: ON-LOGIN
allowed-claim-worlds:
- example_world
wands:
  adminWandID: 374
  infoWandID: 339
private:
  use: true
  allow-outside: false
  allowed-blocks:
  - DISPENSER
  - NOTE_BLOCK
  - BED_BLOCK
  - CHEST
  - WORKBENCH
  - FURNACE
  - JUKEBOX
  - ENCHANTMENT_TABLE
  - BREWING_STAND
  - CAULDRON
  - ENDER_CHEST
  - BEACON
  - TRAPPED_CHEST
  - HOPPER
  - DROPPER
notify:
  region-enter: true
  region-enter-mode: BOSSBAR
  welcome-mode: BOSSBAR
netherProtection:
  maxYsize: 128
  execute-cmd: spawn {player}
flags:
  pvp: false
  chest: false
  lever: false
  button: false
  door: false
  spawn-monsters: true
  spawn-animals: true
  passives: false
  flow: true
  fire: false
  minecart: false
  allow-home: false
flags-configuration:
  change-flag-delay:
    enable: true
    seconds: 10
    flags:
    - pvp
purge:
  enabled: false
  remove-oldest: 90
  ignore-regions-from-players:
update-check:
  enable: true
  auto-update: false
performance:
  disable-onPlayerMoveEvent-handler: false
  disable-PistonEvent-handler: false
