gui-strings:
  value: '&bHabilitado: '
  'true': '&asim'
  'false': '&cnão'
  separator: '&7|'
gui-separator:
  material: STAINED_GLASS_PANE
  data: 5
gui-flags:
  door:
    material: WOOD_DOOR
    name: '&e=> Permite Abrir Portas'
    description: '&6Descrição: &aPermite qualquer player'
    description2: '&aabrir as portas nesta região.'
    description1: ''
    slot: 0
  chest:
    material: CHEST
    name: '&e=> Permite Abrir Baús'
    description: '&6Descrição: &aPermite qualquer player'
    description1: '&acolocar e tirar itens de Baús'
    description2: '&anesta região.'
    slot: 3
  allow-home:
    material: BED
    name: '&e=> Permitir /sethome'
    description: '&6Descrição: &aPermitir qualquer player'
    description1: '&ausar o comando /sethome nesta região.'
    description2: ''
    slot: 2
  pvp:
    material: STONE_SWORD
    name: '&e=> Habilitar PvP'
    description: '&6Descrição: &aHabilita o PvP pra qualquer'
    description1: '&aplayer dentro desta região.'
    description2: ''
    slot: 13
  lever:
    material: LEVER
    name: '&e=> Usar Alavancas'
    description: '&6Descrição: &aPermite qualquer player'
    description1: '&ausar alavancas nesta região.'
    description2: ''
    slot: 5
  spawn-animals:
    material: EGG
    name: '&e=> Spawnar Animais'
    description: '&6Descrição: &aHabilita nascer animais'
    description1: '&apassivos naturalmente ou de spawners'
    description2: '&anesta região.'
    slot: 25
  passives:
    material: SADDLE
    name: '&e=> Interagir com Animais'
    description: '&6Descrição: &aPermitr qualquer player'
    description1: '&ainteragir, dar dano ou matar animais'
    description2: '&anesta região.'
    slot: 24
  button:
    material: WOOD_BUTTON
    name: '&e=> Usar Botões'
    description: '&6Descrição: &aPermite qualquer player'
    description1: '&aa usar botões nesta região'
    description2: ''
    slot: 6
  minecart:
    material: MINECART
    name: '&e=> Permitir Minecarts'
    description: '&6Descrição: &aPermite qualquer player'
    description1: '&acolocar, entrar ou quebrar minecarts'
    description2: '&anesta região.'
    slot: 18
  spawn-monsters:
    material: PUMPKIN
    name: '&e=> Spawnar Monstros'
    description: '&6Descrição: &aHabilitar nascer monstros'
    description1: '&anaturalmente ou de spawners nesta região.'
    description2: ''
    slot: 26
  fire:
    material: BLAZE_POWDER
    name: '&e=> Permitir Dano de Fogo'
    description: '&6Descrição: &aPermitr fogo e explosões'
    description1: '&adestruirem blocos e o fogo se espalhar.'
    description2: ''
    slot: 19
  flow:
    material: WATER_BUCKET
    name: '&e=> Permitir Agua e lava Escorrerem'
    description: '&6Descrição: &aPermite que agua e lava'
    description1: '&aescorram nesta região.'
    description2: ''
    slot: 20
  allow-magiccarpet:
    material: GLASS
    name: '&e=> Permitir Tapete Mágico'
    description: '&6Descrição: &aPermitir players com Tapete Mágico'
    description1: '&aandarem nesta região com ele ativado.'
    description2: ''
    slot: 8
  smart-door:
    slot: 1
    material: IRON_DOOR
    name: '&e=> Abre portas de Ferro'
    description: '&6Descrição: &aPermite membros abrirem'
    description1: '&aportas de ferro e portas duplas juntas.'
    description2: ''
  allow-potions:
    slot: 7
    material: GLASS_BOTTLE
    name: '&e=> Permitir Poções'
    description: '&6Descrição: &aPermite usar ou jogar'
    description1: '&aqualquer tipo de poção por não membros'
    description2: '&anesta região.'
  mob-loot:
    slot: 23
    material: GRASS
    name: '&e=> Mobs Danificar Blocos'
    description: '&6Descrição: &aPermitir mobs danificarem,'
    description1: '&aexplodirem ou removerem blocos desta'
    description2: '&aregião.'
  flow-damage:
    slot: 21
    material: LAVA_BUCKET
    name: '&e=> Liquidos Danificarem Blocos'
    description: '&6Descrição: &aPermite que'
    description1: '&aLava e Agua removam blocos'
    description2: '&aao escorrerem.'
  iceform-entity:
    slot: 22
    material: ICE
    name: '&e=> Permite Formar Gelo por Mobs'
    description: '&6Descrição: &aPermitir formar'
    description1: '&agelo por mobs como Boneco de Gelo.'
    description2: ''
  iceform-player:
    slot: 4
    material: PACKED_ICE
    name: '&e=> Permite Formar Gelo por Players'
    description: '&6Descrição: &aPermite que players'
    description1: '&acom encantamento Passos Gelados'
    description2: '&aformem gelo na agua.'
  allow-fly:
    slot: 16
    material: FEATHER
    name: '&e=> Permitir Fly'
    description: '&6Descrição: &aPermite players com Fly'
    description1: '&ahabilitado voar nesta região.'
    description2: ''
  teleport:
    slot: 10
    material: ENDER_PEARL
    name: '&e=> Permitir Teleporte'
    description: '&6Descrição: &aPermite player nesta região'
    description1: '&ase teleportarem usando itens como ender'
    description2: '&apearl e Fruta do Chorus.'
  clan:
    slot: 14
    material: BOW
    name: '&e=> Compartilhar RP com Clan'
    description: '&6Descrição: &aCompartilha essa RP com'
    description1: '&atodos membros do seu clan de uma vez só,'
    description2: '&acom apenas um clique.'
  ender-chest:
    slot: 13
    material: ENDER_CHEST
    name: '&e=> Permite Abrir EnderChest'
    description: '&bDescrição: &aPermite players abrirem'
    description1: '&aou usarem Baús do Fim nessa RP.'
    description2: ''